server:
  port: 8080

spring:
  freemarker:
      template-loader-path: classpath:/templates/
      prefix:
      suffix: .html
      ##是否允许使用request
      allow-request-override: true
      request-context-attribute: request

      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html;charset=UTF-8
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false

  datasource:
      name: chen
      url: jdbc:mysql://localhost:3306/yhkj?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yhkj.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#logger
Logger:
  level:
    com.yhkj.mapper: info
